### PR TITLE
[BUG] Import via spreadsheet and EAD import bugs

### LINKED ISSUE #33: [BUG] Import via spreadsheet fails after first AO
**Describe the bug**

**To Reproduce**
1. Create a spreadsheet (minimal or extended, csv or xlsx) containing at least 2 AOs to be created
2. Navigate to a resource record
3. Click "Load via spreadsheet" and select your spreadsheet from step 1
4. Follow the progress of the background job, and note that all but the first AO will fail to be created

**Expected behavior**
Spreadsheet AOs all import correctly.

**Screenshots**
Image

**Additional context**
Bug introduced via #20 and changes to how the next_refid is picked up in the `generate_ref_id` method.  The spreadsheet ao's are first all mocked up by the spreadsheet importer (so, now, they're all getting the same `next_refid` to start) and then all imported in one transaction.  The resource record and it's attached `caas_aspace_refid` record isn't refreshed/reloaded before each ao it stubbed leading to this issue.

### LINKED ISSUE #35: [BUG] Importing a large EAD without id attributes on c leads to timeouts
**Describe the bug**
When importing an EAD that contains many (> 30ish) `<c>`s without id attributes (aka, they don't include what will become the aspace `ref_id`) the import progresses very slowly and, ultimately, times out.  Even after cancelling the job, the db hangs with numerous incomplete processes for generating the new `caas_aspace_refid` record.

**To Reproduce**
1. Go to "Create" > "Background Job" > "Import Data"
2. Select "EAD" from the import type dropdown and attach a problem file (check out the file attached to this failed job: https://aspacetest.si.edu/jobs/50198)
3. Click "Start Job"
4. Watch the very slow progress and ultimate timeout.  Confirm db is in a bad state by inspecting the processlist.

**Expected behavior**
Import proceeds as usual without any timeouts.

**Additional context**
This issue stems from the fact that the EAD importer is:
1. Trying to generate `ref_ids` per the plugin logic since the ead file is not being imported with any id attributes at the `<c>`
2. But because of the way the imports are batched in bulk, the plugin is attempting to create a `caas_aspace_refid` record before the required resource is fully created
3. Rather than erroring, the request keeps trying and more and more requests stack up until the db starts timing out.

### PR DESCRIPTION
**Pull request by lorawoodford**
## Description
Changes back to an approach closer to that used and tested prior to the changes in #24 to address #33.  Also adds in a check for the existence of a resource to address #35.  

## Related GitHub Issue
Closes #33 and closes #35 

## Testing
Manually tested locally, automated tests updated and passing.

## Checklist

- [x] ✔️ Have you assigned at least one reviewer?
- [x] 🔗 Have you referenced any issues this PR will close?
- [x] ⬇️ Have you merged the latest upstream changes into your branch? 
- [x] 🧪 Have you added tests to cover these changes?  If not, why:
- [x] 🤖 Have automated checks (if any) passed?  If not, please explain for the reviewer:
- [x] 📘 Have you updated/added any relevant readmes/comments in the codebase?
- [x] 📚 Have you updated/added any external documentation (e.g. Confluence)?

### CODE REVIEW

**Comment by lorawoodford** [comment]
@crugas I'm going to tag you in here to do another review.  There's a fair number of changes here, but only a couple that have a real functional impact and resolve the two linked issues/bugs in the PR description.  A lot of additional changes were tweaks I made to improve readability/maintainability while trying to troubleshoot those two bugs.  I'll try and call out the important bits in line.

File: backend/controllers/caas_next_refid.rb [hunk 1]
```diff
@@ -2,10 +2,16 @@ class ArchivesSpaceService < Sinatra::Base
...
     .description("Get next ref_id for provided resource")
-    .params(["resource_id", Integer, "The resource id", :required => "true"])
+    .params(["resource_id", Integer, "The resource id", :required => "true"],
+            ["repo_id", Integer, "The repository id", :required => "true"])
     .permissions([])
-    .returns([200, "{'resource_id', 'ID', 'next_refid', N}"]) \
+    .returns([200, "(:caas_aspace_refid)"],
+             [400, :error]) \
   do
+    RequestContext.open(:repo_id => params[:repo_id]) do
```
Comment (lorawoodford) [inline backend/controllers/caas_next_refid.rb:11]: This was how I chose to resolve the issue described in #35 .  Those batch imports were failing because this endpoint was attempting to link to a resource record that didn't yet exist because of the way batching works.  Instead, I've just added a check here to error out with a `NotFoundException` in cases where a resource does not exist.  In practice, this means that archival objects will be created with the fallback refid format of `<ead_id>_ref<datestamp>`.  Also, because the `get_or_die` method requires a repo scope, I've had to add that in to the params here and in the ao model that calls the post from the UI.

File: backend/model/archival_object.rb [hunk 2]
```diff
@@ -1,35 +1,33 @@
-require 'net/http'
+require 'ashttp'
 require 'date'
 
-def generate_ref_id(resource)
-  next_refid = get_next_refid(resource)
-
+def generate_ref_id(resource, repo_id)
```
Comment (lorawoodford) [inline backend/model/archival_object.rb:4]: Abandoning the `get_next_refid` approach (that relied on a completed update to the parent resource) resolved #33 .

File: backend/model/archival_object.rb [hunk 3]
```diff
@@ -1,35 +1,33 @@
-require 'net/http'
+require 'ashttp'
```
Comment (crugas) [inline backend/model/archival_object.rb:1]: Just curious why you changed from using net/http to ashttp.

File: backend/controllers/caas_next_refid.rb (hunk 1 above)
Comment (crugas) [reply backend/controllers/caas_next_refid.rb:11]: So when we try to import an EAD file using a background job, because the resource record doesn't exist yet, this will throw the error, but it will still generate the archival objects and new ref IDs (using a datestamp and not the next refID number). Does the resource still get created in this case, just with ref_ids for its archival objects being different than other resources created within ASpace?

File: backend/model/archival_object.rb [hunk 4]
```diff
@@ -1,35 +1,33 @@
...
+    JSON(response.body)['next_refid'] - 1
   rescue
     return DateTime.now.strftime('%Q')
   end
 end
 
-def get_next_refid(resource)
-  resource['caas_next_refid'] ? resource['caas_next_refid']['next_refid'] : 1
-end
+rule_template = ERB.new("<%= resource['ead_id'] %>_ref<%= generate_ref_id(resource, repo_id) %>")
```
Comment (crugas) [inline backend/model/archival_object.rb:17]: I remember seeing this in a ruby tutorial, where <%= %> is ruby's way of embedding code within a string, like f'{function}_hello' f'strings in Python. Is that right?

File: backend/model/archival_object.rb [hunk 5]
```diff
@@ -1,35 +1,33 @@
...
+                               rule_template.result(binding())
                              end,
                              only_on_create: true)
 
 ArchivalObject.auto_generate(property: :ref_id,
                              generator: proc do |json|
+                               repo_id = RequestContext.get(:repo_id)
                                resource = Resource.to_jsonmodel(JSONModel::JSONModel(:resource).id_for(json['resource']['ref']))
-                               "#{resource['ead_id']}_ref#{generate_ref_id(resource)}"
+                               rule_template.result(binding())
```
Comment (crugas) [inline backend/model/archival_object.rb:31]: What does binding() do? Is it related to the [binding](https://ruby-doc.org/core-2.5.4/Binding.html) ruby class?

**Review by crugas — APPROVED** [review]

File: backend/controllers/caas_next_refid.rb (hunk 1 above)
Comment (lorawoodford) [reply backend/controllers/caas_next_refid.rb:11]: Yep, the post fails and exits with an error, then is rescued over in the archival object model: https://github.com/Smithsonian/caas_aspace_refid/blob/33_bulk_import_bug/backend/model/archival_object.rb#L12-L14 

The resource is created, all the aos are created, and the aos are created with datestamp-based ref_id's that aren't tracked in the `caas_aspace_refid` table in the db.  We can always update them later (if needed) via the API.

It is definitely an edge case we'd rarely hit since it would require someone importing an EAD that contains `<c>` tags that don't have id attributes.  Our units very rarely import EAD and - I'd suspect - even more rarely import EADs that don't contain id attributes.  But we can iterate on this in the future if we find this is an issue.

File: backend/model/archival_object.rb (hunk 3 above)
Comment (lorawoodford) [reply backend/model/archival_object.rb:1]: No particularly good reason.  This is one of those holdovers of "things I tried while attempting to fix the bug and decided were worth keeping."  At the end of the day the custom ASHTTP class just calls Net:HTTP but with a few extra opts that can be passed along (like enabling ssl).  We might want that extensibility in the future, so I kept this change as a "won't hurt, might help."  This is also how the Top Containers model is implemented: https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/top_container.rb#L293-L300

File: backend/model/archival_object.rb (hunk 4 above)
Comment (lorawoodford) [reply backend/model/archival_object.rb:17]: Sort of.  ERB is one ruby-based way to implement templating (it stands for "embedded Ruby").  There are other templating approaches common in Ruby/Rails apps like haml or slim, but aspace uses ERB.  The true equivalent to your Python example would be string interpolation in ruby which you'll see like:

```
"my string #{embedded_ruby_function} is fun!"
```

where `embedded_ruby_function` is just some valid ruby method you want run in the context of that string.

But ERB templating lets us construct valid HTML as a template to be called elsewhere, so that's why we use it here.

I made this change to move us closer to the example provided/supported in ArchivesSpace core code: https://github.com/archivesspace/archivesspace/blob/master/plugins/refid_rules/backend/model/archival_object.rb

File: backend/model/archival_object.rb (hunk 5 above)
Comment (lorawoodford) [reply backend/model/archival_object.rb:31]: Yep, exactly.  `binding` is a whole thing - you might be most familiar with it from `binding.pry` which is great for debugging things.  This just says "grab the result of our rule template at this point and scope and save it to use later on."
